name: build-and-test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          python-version: [3.8]
          django-version: [3.2]
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        run: |
          python -m pip install --upgrade pip
          pip install -r test_reqs.txt
          python ./runtests.py
